-- -----------------------------------------------------------------------------
--             Insertion des données dans la BDD Biblioweb
-- -----------------------------------------------------------------------------
--      Nom de la base : Biblioweb
--      Projet : Projet Individuel
--      Auteur : NOSELLAL
--      Date de dernière modification : 24/5/2018
-- -----------------------------------------------------------------------------