-- -----------------------------------------------------------------------------
--             Test des règles de gestion dans la BDD Biblioweb
-- -----------------------------------------------------------------------------
--      Nom de la base : Biblioweb
--      Projet : Projet Individuel
--      Auteur : NOSELLAL
--      Date de dernière modification : 25/5/2018
-- -----------------------------------------------------------------------------
